// small datum actions
export const SET_ADDRESS = "SET_ADDRESS";
export const SET_LOCATION = "SET_LOCATION";
export const SET_CONTACTS = "SET_CONTACTS";
export const ALLOW_LOCATION_ACCESS = "ALLOW_LOCATION_ACCESS";
export const DENY_LOCATION_ACCESS = "DENY_LOCATION_ACCESS";
export const SHOW_OPTIONS = "SHOW_OPTIONS";
export const HIDE_OPTIONS = "HIDE_OPTIONS";

// big data actions
export const PEDESTRIAN_COUNTS_LOADING = "PEDESTRIAN_COUNTS_LOADING";
export const ADD_PEDESTRIAN_COUNTS = "ADD_PEDESTRIAN_COUNTS";
export const PEDESTRIAN_COUNTS_FAILED = "PEDESTRIAN_COUNTS_FAILED";
export const PSO_STATIONS_LOADING = "PSO_STATIONS_LOADING";
export const ADD_PSO_STATIONS = "ADD_PSO_STATIONS";
export const PSO_STATIONS_FAILED = "PSO_STATIONS_FAILED";
export const ADD_EMERGENCY_CONTACT = "ADD_EMERGENCY_CONTACT";
export const REMOVE_EMERGENCY_CONTACT = "REMOVE_EMERGENCY_CONTACT";
